### ISSUE TITLE
Error while opening file

### ISSUE THREAD

**Issue by saukkico** [yattee/yattee#828]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Some videos won’t play. On Apple TV I get no error messages, it just doesn’t play. On iPhone I get message ”Error while opening file”. 
Then after a while if I try to play the video again, it suddenly works. 
Here’s one example. First it didn’t work, but then after about 15 minutes it suddenly works. 
https://www.youtube.com/watch?v=ZOwhThUc3DI

This is quite weird, because most videos does work normally and only few has this issue. I have no idea if this is a Yattee issue, Invidious issue or Youtube issue. 

I’m using selfhosted Invidious instance. 

![IMG_1584](https://github.com/user-attachments/assets/1c4c74e3-a5fd-4ac5-bab7-e842fca53055)

### Expected Behavior

All videos should play normally. 

### Device & OS Version

Apple TV 4k first gen, latest OS & iPhone 15 latest OS. 

### App Build

196

**Comment by g3rhard** [comment]
Have the same issue, but currently solved (looks like) on Invidious instance by adding additional helper: https://github.com/iv-org/documentation/blob/master/docs/installation.md#docker-compose-method-production
```
  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
 ```
Also, helm chart available (https://github.com/g3rhard/helm-invidious), as example

Looking for something else, what should be fixed there - for now nothing suspicious in Invidious logs...
