### ISSUE TITLE
Thumbnails not loading on Invidious instance

### ISSUE THREAD

**Issue by ndrew222** [yattee/yattee#862]
### Guidelines

- [x] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Thumbnails don’t load

I’m running a local invidious instance on my desktop, and connecting to it works fine. 
The only problem is most images don’t load (thumbnails, profile pictures). I will also note that thumbnails load fine on the web client locally on the desktop. 

### Expected Behavior

Thumbnails display properly

### Device & OS Version

iPad Pro (11-inch) (2nd Generation), iPadOS 18.1.1 | iPhone SE (A2783), iOS 18.2.1

### App Build

174

### Screenshots, Videos and other files

![Image](https://github.com/user-attachments/assets/158d0287-7d60-46c6-8e09-90341b098548)
![Image](https://github.com/user-attachments/assets/12f19c86-9303-4af4-864d-0f5147c309be)

**Comment by bbsixzz** [comment]
Same, I'm running with invidious companion version: 2025.03.26-23ff613 @ master

**Comment by bbsixzz** [comment]
Thank you that did the trick, I switched from sig_helper to companion and I forgot to migrate these settings.

**Comment by ndrew222** [comment]
I don’t use invidious companion (don’t know what it’s for) how do I fix this?

**Comment by bbsixzz** [comment]
https://docs.invidious.io/companion-installation/

**Comment by ndrew222** [comment]
Fixed it without invidious companion. 
Here’s my docker-compose (without the passwords lol)
```yaml
services:
  invidious:
    # image: quay.io/invidious/invidious:latest
    image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: "CHANGE_ME"
        po_token: "CHANGEME"
        external_port: 3000
        domain: "dietpi"
        # https_only: false
        # statistics_enabled: false
        hmac_key: "CHANGEME"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
